project:
  type: website
  output-dir: docs

website:
  title: "Henry Yang - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes
        menu:
        - href: weekly-notes/week-01-notes.qmd
          text: Week 1
        - href: weekly-notes/week-02-notes.qmd
          text: Week 2
        - href: weekly-notes/week-03-notes.qmd
          text: Week 3
        - href: weekly-notes/week-04-notes.qmd
          text: Week 4
        - href: weekly-notes/week-05-notes.qmd
          text: Week 5
        - href: weekly-notes/week-06-notes.qmd
          text: Week 6
        - href: weekly-notes/week-07-notes.qmd
          text: Week 7
        - href: weekly-notes/week-09-notes.qmd
          text: Week 9
      - text: Labs
        menu:
        - href: Labs/lab_0/script/lab0_template.qmd
          text: Lab 0
      - text: Assignments
        menu:
        - href: Labs/lab_1/script/Yang_Henry_Assignment1.qmd
          text: "Assignment 1: Census Data Exploration"
        - href: Labs/lab_2/script/Yang_Henry_Assignment2.qmd
          text: "Assignment 2: Spatial Analysis and Visualization"
      - text: Midterm
        menu: 
          - href: midterm/appendix/Yang_Henry_Midterm_appendix.qmd
            text: "Single-Family Home Price Prediction in Philadelphia"
          - href: midterm/slides/Yang_Henry_Midterm_slides.qmd
            text: "Improving Property Tax Assessments"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
